### ISSUE TITLE
MacOS Unable to load shared library 'libvirt-0.dylib'

### ISSUE THREAD

**Issue by bman46** [IDNT/AppBasics-Virtualization-Libvirt#2]
On macOS, the library throws a DLL not found exception for the `libvirt-0.dylib` library. When installed on Mac through brew, the directory that it is located in is (for me atlest) `/opt/homebrew/Cellar/libvirt/7.9.0/lib` and the file is named `libvirt.0.dylib`. I managed to work around the not found error by adding this DLL to the project. However, since I am on an M1 mac, the DLL is complied for arm and i receive the error `tried: 'liblibvirt-0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))`. Is there any work arounds for ARM builds at the moment?

**Comment by mazocode** [comment]
I currently have no way to test this. The examples all have x86 configured as target but theoretically it should be possible to recompile for ARM64.

**Comment by bman46** [comment]
Ok, ill try to recompile it and see how that goes.
